-- MySQL Script generated by MySQL Workbench
-- Wed Apr 21 14:38:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema propertiesdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema propertiesdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `propertiesdb` DEFAULT CHARACTER SET utf8 ;
USE `propertiesdb` ;

-- -----------------------------------------------------
-- Table `propertiesdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertiesdb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `enabled` VARCHAR(45) NULL,
  `contact_no` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertiesdb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertiesdb`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertiesdb`.`properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertiesdb`.`properties` (
  `property_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `price` BIGINT NULL,
  `verified` TINYINT NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`property_id`, `users_user_id`),
  INDEX `fk_properties_users_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_properties_users`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `propertiesdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `propertiesdb`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `propertiesdb`.`users_roles` (
  `users_user_id` INT NOT NULL,
  `roles_role_id` INT NOT NULL,
  PRIMARY KEY (`users_user_id`, `roles_role_id`),
  INDEX `fk_users_has_roles_roles1_idx` (`roles_role_id` ASC) VISIBLE,
  INDEX `fk_users_has_roles_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_roles_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `propertiesdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_roles_roles1`
    FOREIGN KEY (`roles_role_id`)
    REFERENCES `propertiesdb`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
